


system_prompt = """# Role You are a data migration agent. Your job is to consolidate athlete records from three triathlon data sources (IRONMAN race results, USAT membership data, Strava activities) into a unified SQLite database.

# Source Data

The data comes from three different sources. The same athletes appear across multiple sources, but with different identifiers and naming conventions in each. There is no shared join key between sources; matching must be inferred from data values.

1. IRONMAN: generally clean structured data; expect occasional partial records (DNFs).
2. USAT: membership rather than race data; some inconsistency in name formatting and nicknames.
3. Strava: user-generated content; treat activity titles and metadata as self-reported and not independently verified.

# Target Schema

Produce a SQLite database with these four tables. unified_id, race_id, and result_id are autogenerated by SQLite. An athlete has has_official_results = 1 if they appear in IRONMAN data (including DNFs), and 0 otherwise. Here are their schemas

CREATE TABLE athletes (
    unified_id           INTEGER PRIMARY KEY,
    canonical_name       TEXT NOT NULL,
    dob                  TEXT NOT NULL,
    country              TEXT NOT NULL,
    age_group_2024       TEXT,
    ironman_id           TEXT,
    usat_member_number   TEXT,
    strava_username      TEXT,
    has_official_results INTEGER NOT NULL
);

CREATE TABLE races (
    race_id        INTEGER PRIMARY KEY,
    race_name      TEXT NOT NULL,
    race_date      TEXT NOT NULL,
    distance_type  TEXT NOT NULL
);

CREATE TABLE race_results (
    result_id            INTEGER PRIMARY KEY,
    unified_id           INTEGER NOT NULL,
    race_id              INTEGER NOT NULL,
    bib_number           INTEGER,
    swim_time_seconds    INTEGER,
    bike_time_seconds    INTEGER,
    run_time_seconds     INTEGER,
    finish_time_seconds  INTEGER,
    overall_place        INTEGER,
    status               TEXT NOT NULL,
    source               TEXT NOT NULL,
    FOREIGN KEY (unified_id) REFERENCES athletes(unified_id),
    FOREIGN KEY (race_id) REFERENCES races(race_id)
);

CREATE TABLE source_metadata (
    unified_id            INTEGER PRIMARY KEY,
    in_ironman            INTEGER NOT NULL,
    in_usat               INTEGER NOT NULL,
    in_strava             INTEGER NOT NULL,
    strava_activity_count INTEGER NOT NULL DEFAULT 0,
    notes                 TEXT,
    FOREIGN KEY (unified_id) REFERENCES athletes(unified_id)
);

# Methodology

Approach the work in three phases:

1. To examine source CSVs, use two tools in sequence: First call inspect_csv to see columns, row count, and a 5-row sample. Then call read_csv to load all rows when you need to process the full file. Always inspect_csv first to understand the structure; always read_csv before inserting data into the database so you have visibility into every row.

2. Reason about cross-source athlete matching using available signals such as names (in their multiple formats), dates of birth, countries, and patterns of race participation. Use whatever combination of signals is present rather than relying on any single field.

3. Populate the database in dependency order: athletes, then races, then race_results, then source_metadata. The order is required because foreign keys cannot reference rows that do not yet exist.

Before each insert, briefly state what you are inserting and what evidence supports your decision, especially for unusual cases. Make your reasoning visible in the conversation.

Treat each data source by its authoritative scope. IRONMAN is the source of truth for race results. USAT is authoritative for membership. Strava records personal activity but does not verify race participation — a self-reported activity titled as a race finish does not establish that the athlete actually raced. Trust each source only for what it actually verifies.

For unusual or ambiguous cases — DNFs, athletes appearing in only some sources, ambiguous matches, self-reported activity that conflicts with official records — populate the source_metadata.notes field with a clear explanation of the situation and a suggested action for a human reviewer. For routine cases, leave notes NULL.


# Edge Cases

Names are not necessarily unique identifiers, cross reference using other signals such as DOB and country.

Athletes may not appear in every data source. Continue to handle them, do not discard them.  

Name formatting may not be consistent across sources including capitalization, nicknames, apostrophes, formal vs. informal, and athletes may appear under handles with no name overlap at all. Use other signals (DOB, country, race history, etc) to confirm matches. 

Self-reporting race results does not make them valid. Flag with a note rather than treat as official. 

Records may have non-standard statuses (incomplete, withdrawn, partial). Preserve them with appropriate status rather than silently dropping.

# Done Condition

Before declaring the work complete, verify the database using run_query:

- Every athlete identified during inspection is represented in the database, either as a row in athletes or via source_metadata.
- Every unified_id in race_results exists in athletes.
- Every race_id in race_results exists in races.
- Every unified_id in source_metadata exists in athletes.

When all checks pass, produce a brief summary of the work and stop.



"""

import json
import os
import time
import anthropic
import tools as T
import time

tools = [
    {
        "name": "inspect_csv",
        "description": "Return the column names, total row count, and first 5 rows of a CSV file.",
        "input_schema": {
            "type": "object",
            "properties": {
                "filepath": {
                    "type": "string",
                    "description": "Path to the CSV file to inspect."
                }
            },
            "required": ["filepath"]
        }
    },
    {
        "name": "read_csv",
        "description": "Read all rows from a CSV file. Returns the complete data as a list of row dicts. Use this after inspect_csv when you need full data access.",
        "input_schema": {
            "type": "object",
            "properties": {
                "filepath": {
                    "type": "string",
                    "description": "Path to the CSV file to open."
                }
            },
            "required": ["filepath"]
        }
    },
    {
        "name": "insert_athlete",
        "description": "Insert a row into the athletes table and return the new unified_id.",
        "input_schema": {
            "type": "object",
            "properties": {
                "canonical_name":       {"type": "string",  "description": "Full canonical name of the athlete."},
                "dob":                  {"type": "string",  "description": "Date of birth (YYYY-MM-DD)."},
                "country":              {"type": "string",  "description": "Country code or name."},
                "age_group_2024":       {"type": "string",  "description": "Age group for the 2024 season."},
                "ironman_id":           {"type": "string",  "description": "IRONMAN identifier."},
                "usat_member_number":   {"type": "string",  "description": "USAT membership number."},
                "strava_username":      {"type": "string",  "description": "Strava username."},
                "has_official_results": {"type": "integer", "description": "1 if the athlete has official IRONMAN results, 0 otherwise."}
            },
            "required": ["canonical_name", "dob", "country", "has_official_results"]
        }
    },
    {
        "name": "insert_race",
        "description": "Insert a row into the races table and return the new race_id.",
        "input_schema": {
            "type": "object",
            "properties": {
                "race_name":     {"type": "string", "description": "Official name of the race."},
                "race_date":     {"type": "string", "description": "Date the race took place (YYYY-MM-DD)."},
                "distance_type": {"type": "string", "description": "Distance category (e.g. Full, 70.3)."}
            },
            "required": ["race_name", "race_date", "distance_type"]
        }
    },
    {
        "name": "insert_race_result",
        "description": "Insert a row into the race_results table and return the new result_id.",
        "input_schema": {
            "type": "object",
            "properties": {
                "unified_id":          {"type": "integer", "description": "Foreign key to athletes.unified_id."},
                "race_id":             {"type": "integer", "description": "Foreign key to races.race_id."},
                "bib_number":          {"type": "integer", "description": "Athlete bib number."},
                "swim_time_seconds":   {"type": "integer", "description": "Swim split in seconds."},
                "bike_time_seconds":   {"type": "integer", "description": "Bike split in seconds."},
                "run_time_seconds":    {"type": "integer", "description": "Run split in seconds."},
                "finish_time_seconds": {"type": "integer", "description": "Total finish time in seconds."},
                "overall_place":       {"type": "integer", "description": "Overall finishing position."},
                "status":              {"type": "string",  "description": "Finish status (e.g. Finished, DNF)."},
                "source":              {"type": "string",  "description": "Data source (e.g. ironman, strava)."}
            },
            "required": ["unified_id", "race_id", "status", "source"]
        }
    },
    {
        "name": "insert_source_metadata",
        "description": "Insert a row into the source_metadata table tracking which sources contain this athlete.",
        "input_schema": {
            "type": "object",
            "properties": {
                "unified_id":            {"type": "integer", "description": "Foreign key to athletes.unified_id."},
                "in_ironman":            {"type": "integer", "description": "1 if athlete appears in IRONMAN data, else 0."},
                "in_usat":               {"type": "integer", "description": "1 if athlete appears in USAT data, else 0."},
                "in_strava":             {"type": "integer", "description": "1 if athlete appears in Strava data, else 0."},
                "strava_activity_count": {"type": "integer", "description": "Number of Strava activities for this athlete."},
                "notes":                 {"type": "string",  "description": "Free-text notes for ambiguous or unusual cases."}
            },
            "required": ["unified_id", "in_ironman", "in_usat", "in_strava", "strava_activity_count"]
        }
    },
    {
        "name": "run_query",
        "description": "Run a read-only SELECT query against the SQLite database and return the result rows.",
        "input_schema": {
            "type": "object",
            "properties": {
                "sql": {
                    "type": "string",
                    "description": "A SELECT SQL statement to execute."
                }
            },
            "required": ["sql"]
        }
    }
]

TOOL_DISPATCH = {
    "inspect_csv":            lambda args: T.inspect_csv(**args),
    "read_csv":               lambda args: T.read_csv(**args),
    "insert_athlete":         lambda args: T.insert_athlete(**args),
    "insert_race":            lambda args: T.insert_race(**args),
    "insert_race_result":     lambda args: T.insert_race_result(**args),
    "insert_source_metadata": lambda args: T.insert_source_metadata(**args),
    "run_query":              lambda args: T.run_query(**args),
}


def dispatch(tool_name, tool_input):
    fn = TOOL_DISPATCH.get(tool_name)
    if fn is None:
        return f"Unknown tool: {tool_name}"
    try:
        result = fn(tool_input)
        return json.dumps(result, default=str)
    except Exception as e:
        return f"Error: {e}"


def run_agent():
    client = anthropic.Anthropic()
    messages = [
        {"role": "user", "content": "Begin the data migration. The three source CSVs are at data/athletes_ironman.csv, data/athletes_usat.csv, and data/athletes_strava.csv. The target SQLite database is output.db. Inspect each source first, then unify the records into the database following the methodology and edge cases in your system prompt."}
    ]
    max_turns = 50

    for turn in range(max_turns):
        response = client.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=16384,
            system=system_prompt,
            tools=tools,
            messages=messages,
        )

        # Append assistant reply
        messages.append({"role": "assistant", "content": response.content})

        for block in response.content:
            if block.type == "text":
                print(f"\n[Turn {turn + 1}] {block.text}\n")
            elif block.type == "tool_use":
                print(f"  → Calling {block.name}({block.input})")

        # Check for tool use blocks
        tool_use_blocks = [b for b in response.content if b.type == "tool_use"]
        if not tool_use_blocks:
            break

        # Dispatch each tool call and build the tool results
        tool_results = []
        for block in tool_use_blocks:
            result = dispatch(block.name, block.input)
            tool_results.append({
                "type": "tool_result",
                "tool_use_id": block.id,
                "content": result,
            })

        messages.append({"role": "user", "content": tool_results})

        time.sleep(5)

    # Write conversation log
    os.makedirs("runs", exist_ok=True)
    timestamp = time.strftime("%Y%m%d_%H%M%S")
    log_path = f"runs/agent_run_{timestamp}.jsonl"
    with open(log_path, "w") as f:
        for msg in messages:
            f.write(json.dumps(msg, default=str) + "\n")

    print(f"Agent finished after {turn + 1} turns. Log: {log_path}")


if __name__ == "__main__":
    run_agent()